### ISSUE TITLE
Getting ImportError with aws login configure command

### ISSUE THREAD

**Issue by cmaturi** [techservicesillinois/awscli-login#11]
System Windows 10
Python version -- 3.6.3
Receiving ImportError message when I entered the command 
`$` `aws` `login` `configure` 
![importerror](https://user-images.githubusercontent.com/8779379/40325287-c37f44d6-5d00-11e8-81fb-ce5880479d75.png)

**Comment by ddriddle** [comment]
@cmaturi are still having this issue?

**Comment by cmaturi** [comment]
This issue is still occurring. I tried installing the plug in today and got the Import error message.
System Windows 10
Python version -- 3.6.3
Receiving ImportError message when I entered the command
`$ aws login configure`
![windows_awscli-plugin](https://user-images.githubusercontent.com/8779379/48514589-44784700-e824-11e8-85e2-dd0e0fd86196.PNG)

**Comment by ddriddle** [comment]
@cmaturi can you please try running the following commands:
```
aws --version
```
and
```
python -c "import awscli_login"
```

**Comment by cmaturi** [comment]
After removing the plugin from the `~/.aws/config`
```
C:\Users\cmaturi\.aws>aws --version
aws-cli/1.15.16 Python/2.7.9 Windows/8 botocore/1.10.16
```

**Comment by joshuaganger** [comment]
module 'os' has no attribute 'fchmod'

I've encountered this issue as well.  I believe it is related to Windows file permissions.  Did you find a solution?  I saw a workaround posted on another project: https://github.com/costela/wile/issues/3 but I'm thinking this ignores the intentions of setting the mode on the file in the first place.  Any suggestions?
