### ISSUE TITLE
Daemon loses sync when machine sleeps

### ISSUE THREAD

**Issue by ckuehn-uiuc** [techservicesillinois/awscli-login#12]
When my PC wakes from sleep mode, I find that awscli_login believes I'm still logged in even though my credentials have expired.

Symptoms:
1. Daemon is running (according to ps)
2. AWS rejects API calls: "An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired."
3. `aws login` reports "Already logged in!"

Workaround:
`aws logout; aws login`

**Comment by edthedev** [comment]
#76 has additional diagnostic logs that are likely related.

**Comment by edthedev** [comment]
#88 May help us with investigating this in the future.

And @ddriddle's comment here might be an important part of this:
https://github.com/techservicesillinois/awscli-login/issues/23#issuecomment-777193220

**Comment by edthedev** [comment]
Pushed the wrong 'comment' button.

**Comment by JonRoma** [comment]
For whatever it's worth, my failures to renew have been while I was continuously working on the Mac – i.e., the computer never went to sleep. This sort of defies logic. :-)

**Comment by edthedev** [comment]
Per recent discussion, work in the AWS API V2 support milestone might allow us to revisit this. Can't promise a solution right now, but we're still thinking about this one.

**Comment by edthedev** [comment]
@ckuehn-uiuc The daemon will be retired with the next release, to allow AWS CLI V2 support. Refresh will still be supported, and won't require the daemon. See #106 for details.
