### ISSUE TITLE
trouble installing on wsl / ubuntu

### ISSUE THREAD

**Issue by jtgorman** [techservicesillinois/awscli-login#122]
Trying to set this up on a newish windows machine, using wsl (ubuntu).

Ok, so, everthing seems to go ok...until I get to step to configure the plugins. 

~$ aws configure set plugins.login awscli_login.plugin
Traceback (most recent call last):
  File "/home/jtgorman/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/jtgorman/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/jtgorman/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/home/jtgorman/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 78, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "/home/jtgorman/.local/lib/python3.8/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/home/jtgorman/.local/lib/python3.8/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
ModuleNotFoundError: No module named 'awscli_login.plugin'

I feel like I'm missing something obvious. I might try again using a venv .

This doesn't seem to be the same errors as in the bottom of the Known Issues, but I could be missing something

**Comment by edthedev** [comment]
@jtgorman We had to split some built in functionality into plugins in order to support AWS CLI V2, so it's possible this is either a path issue or just a bug related to the change.

We will attempt to replicate.

Are you using WSL version 2?

**Comment by edthedev** [comment]
@jtgorman We do usually use a venv, so it's possible that is related.

**Comment by jtgorman** [comment]
Yup, using wsl2

Won't get a chance to try a venv till tomorrow or next week probably, but let you know results of that too

**Comment by zdc217** [comment]
Hey Jon, 

Are you trying to install from the pip package or from the source code?

**Comment by jtgorman** [comment]
This time around I used pip, but I kinda have probably made a bit of a hash of it...

Tried...

1) downloading aws v2 installer, running that. Got part way along, may have missed the step to configure. Basically some comamnds didn't work, I went and looked at the issues and saw it looks like v2 support may not be there yet.

2) Downloaded from aws v1,  didn't work

3) tried pip.

It's possible something is in an unclean state and didn't quite get cleaned up.  I'll try with a venv tomorrow or early next week and see if that's better. I

**Comment by jtgorman** [comment]
The source and pip errors are the same btw from what I rmember. The original aws v2 just didn't seem to have the command from what I remmber.

**Comment by edthedev** [comment]
@jtgorman You probably got the install fine on V2. Some previous commands do not work with AWS CLI V2, due to changes in V2.

**Comment by edthedev** [comment]
@jtgorman and I are plotting to take a deeper look on Thursday afternoon,.

**Comment by jtgorman** [comment]
SecDev group helped me out - I was more on the cutting edge then I realized when I started trying to do instructions on this page -> instructinos from PyPi worked. See https://pypi.org/project/awscli-login/

**Comment by edthedev** [comment]
We have seen this again since when downgrading back to the previous version.

The solution is to clear out the `plugin = awscli_login.plugin` line from `.aws/config`.
