### ISSUE TITLE
AWS ECP endpoint issue

### ISSUE THREAD

**Issue by jpburke** [techservicesillinois/awscli-login#13]
I opened a support ticket with AWS and they confirmed that the AWS Console SP does not support an ECP endpoint. It was my understanding the both the IDP and SP need to support the ECP binding. How are you configuring the Shibboleth IDP to avoid this constraint?

Thanks.

**Comment by ddriddle** [comment]
Sorry for the delay in responding to this issue.

You are correct that the Amazon SP does not support ECP. Neither does ECP support IdP initiated SSO. The way this works is that the plugin creates an unauthenticated AuthNRequest on behalf of the Amazon SP which is sent to the Shibboleth IdP. The IdP then returns the SAMLResponse to the plugin which submits the SAMLResponse and a role selection to Amazon's STS API which then returns temporary AWS credentials on success.

The reason this works is that the plugin has no need to directly communicate with the Amazon SP. It merely needs a valid SAMLResponse from the IdP that the Amazon STS API will accept.

I recently gave a presentation on the awscli-login plugin and how it works with the IdP and SP. Take a look at [slides](https://docs.google.com/presentation/d/1XIXFJN1UEa4qrkcYrEJl7XM1WI9UrbS37f_ZBh7OnE0/view#slide=id.g459b347ee8_1_171) 45 through 55.

If you need more details our IdP operator @kwessel should be able to help you.

**Comment by edthedev** [comment]
This appears to be resolved. Can re-open and update our docs if there's interest, but otherwise will close for now.
