### ISSUE TITLE
How to update the stored password

### ISSUE THREAD

**Issue by yoonlees** [techservicesillinois/awscli-login#14]
After changing the AD password, the app can't update the password.  The login fails when you tried and the workaround was changing the Enable Keyring to False and type in the password in the prompt.

**Comment by ddriddle** [comment]
@yoonlees to set you password you need to know the hostname for your IdP and your Shibboleth username. To change your password type the following command:
```
keyring set awscli_login username@hostname_of_your_IdP
```
For a U of I user you would type:
```
keyring set awscli_login netid@shibboleth.illinois.edu
```
You may also retrieve your password with this command:
```
keyring get awscli_login username@hostname_of_your_IdP
```
You may be prompted for your user login password by your operating system depending on how you have your key store configured.

**Comment by JonRoma** [comment]
Close this issue once @JonRoma 's fork is integrated into master.

**Comment by ddriddle** [comment]
@JonRoma FYI if you add the keyword "closes", "fixes", "resolves", etc. in the pull request or commit message then this issue would be resolved automatically on merge. See [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/) for details.

**Comment by JonRoma** [comment]
That's annoying!
