### ISSUE TITLE
Add stale issue automation

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#181]
**Is your feature request related to a problem? Please describe.**

We have CI/CD steps in other repositories that automatically label, notify, and eventually close issues that a growing stale.
It helps keep the backlog fresh, relevant and focused.

**Describe the solution you'd like**

We should implement the same stale issue handling recipe here, to keep this effort focused and active.

**Describe alternatives you've considered**

Doing nothing.

**Additional context**

A copy of our recipe is here:
https://github.com/techservicesillinois/SecOps-Tools/blob/main/.github/workflows/cleanup.yml

**Comment by mpitcel** [comment]
Task List:

- [ ] Add stale issue automation per this recipe: https://github.com/techservicesillinois/SecOps-Tools/blob/main/.github/workflows/cleanup.yml
- [ ] Test the automation
