### ISSUE TITLE
Default region handling

### ISSUE THREAD

**Issue by cslawrence-uiowa** [techservicesillinois/awscli-login#20]
When I have everything configured, I have to specify the region every time I run the AWS CLI. Is there a way to have the awscli-login plugin pass user-specified default region?

**Comment by ddriddle** [comment]
You may set your region per profile using the standard AWS CLI utility. For the currently selected profile use the following command:
```
$ aws configure
AWS Access Key ID [None]: 
AWS Secret Access Key [None]: 
Default region name [None]: your_aws_region
Default output format [None]:
```
If you want to set the region for another profile use the following command:
```
$ aws configure --profile your_profile_name
AWS Access Key ID [None]: 
AWS Secret Access Key [None]: 
Default region name [None]: your_aws_region
Default output format [None]:
```
You may also set an environment variable like this on Unix/Linux/Mac OS X:
```
export AWS_REGION=your_aws_region
```
or on Windows:
```
set AWS_REGION=your_aws_region
```
You may read more about the AWS configuration tool, named profiles, and setting a region at the Amazon documentation [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration).

If this information is not helpful, please explain your use case in greater detail.

**Comment by cslawrence-uiowa** [comment]
Okay, so you're just pulling from what's already present from aws config. That helps, thanks. We were approaching this from the angle that a user might start using the AWS CLI without having touched it before, and jumping right into awscli-login. We'll keep this in mind as we build docs for our users.
