### ISSUE TITLE
Add stand alone support

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/awscli-login#214]
Update awscli-login so that the `aws-login` script can be used independelty of `aws` in case the plugin mechanism is completely removed by `aws`.

---------------

Team discussion update - to close this out, we will need to pivot away from any reliance on `plugin` mode, since the official support from AWS is not there on V2. Don't anticipate significant usability impact, just need to think through and make the code changes.

- Make use as a plugin completely optional.
- Clarify in README that use in `plugin` mode with AWS CLI V2 is not officially supported.

_Originally posted by @edthedev in https://github.com/techservicesillinois/awscli-login/issues/106#issuecomment-1405279797_

**Comment by ddriddle** [comment]
@edthedev how strongly do you still feel about requiring stand alone support for `awscli-login` for V2? I now feel that PR #106 is ready to be merged. Do you want to require stand alone support before we make an official release? I'm inclined at the moment to go ahead with a release as is.

**Comment by edthedev** [comment]
> [@edthedev](https://github.com/edthedev) how strongly do you still feel about requiring stand alone support for `awscli-login` for V2? I now feel that PR [#106](https://github.com/techservicesillinois/awscli-login/pull/106) is ready to be merged. Do you want to require stand alone support before we make an official release? I'm inclined at the moment to go ahead with a release as is.

Just updating this ticket, per our other discussions - yes, we're pursuing a release, and can drop this desired feature.
