### ISSUE TITLE
Fails to work with YubiKey after UIUC IdP upgrade

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/awscli-login#25]
Previously, we used a separate module that used the following headers:
```
X-Shiboleth-Duo-Factor
X-Shiboleth-Duo-Passcode
```
The new Shibboleth IdP 3.4 changed the header names:
```
X-Shibboleth-Duo-Factor
X-Shibboleth-Duo-Passcode
```
We need to make the headers configurable by the end user.

**Comment by ddriddle** [comment]
```
+++ /Users/ddriddle/.pyenv/versions/3.5.2/lib/python3.5/site-packages/awscli_login/config.py	2019-02-28 15:54:09.000000000 -0600
@@ -281,9 +281,9 @@
             self.raise_if_factor_invalid()
 
         if self.is_factor_valid():
-            headers['X-Shiboleth-Duo-Factor'] = self.factor
+            headers['X-Shibboleth-Duo-Factor'] = self.factor
             if not first_pass or self.factor == 'passcode':
-                headers['X-Shiboleth-Duo-Passcode'] = input('Code: ')
+                headers['X-Shibboleth-Duo-Passcode'] = input('Code: ')
 
         return self.username, self.password, headers
 
```

**Comment by ddriddle** [comment]
Note that I had the following line in my `/etc/hosts` file:

```
# Chicago
204.93.1.149   shibboleth.illinois.edu
```

When I comment this line out everything works fine!

**Comment by dmrzzz** [comment]
It looks like you already have a solution to bring the headers in line with latest IdP.  Any chance we could get an updated release?

**Comment by ddriddle** [comment]
@dmrzzz expect an update be the end of the week.

**Comment by sosumi** [comment]
In addition to this issue, it appears that there may be a bug in the default Duo configuration for the Shibboleth IdP that would prevent the selection of "passcode" as a factor. See: https://issues.shibboleth.net/jira/browse/IDP-1448

**Comment by ddriddle** [comment]
The release 0.1.0a6 of awscli-login resolves this issue. Sorry for the delayed release.
