### ISSUE TITLE
2 Factor Authentication with passcode does not work

### ISSUE THREAD

**Issue by jmtroy** [techservicesillinois/awscli-login#29]
The 2 factor authentication does not seem to work with the passcode option.  

$ aws login
Username [h****2]: h****2  
Password: 
Factor: passcode
Code: 3***02
Authentication failed!

We (library IT) have not had any issues with the push option.  Another test by different user (below) it seem to ignore the passcode option, and set a push anyway.

$ aws login
Password: 
Factor: passcode
Code: 3*******5
< at this point seem to ignore the passcode and sent a push to my device>
Please choose the role you would like to assume:
     Account: 083*********1
         [ 0 ]: Admins
     Account: 256*********9
         [ 1 ]: LibraryIT
     Account: 378*********6
         [ 2 ]: TechServicesStaff
     Account: 721*********9
         [ 3 ]: LibraryIT
         [ 4 ]: MedusaAdmins
     Account: 974*********5
         [ 5 ]: MedusaAdmins
Selection: 3

**Comment by hading** [comment]
I'm the one who brought this to jmtroy's attention. The particular token that I'm trying to use (if relevant) is the OTP c100. It has also been pointed out to us by another member of our group that this may be related to or the same as https://github.com/techservicesillinois/awscli-login/issues/25.

**Comment by sosumi** [comment]
In addition to issue #25 (correcting the spelling of the X-Shibboleth-* headers), it appears that there may be a bug in the default Duo configuration for the Shibboleth IdP that would prevent the selection of "passcode" as a factor. See: https://issues.shibboleth.net/jira/browse/IDP-1448

**Comment by ddriddle** [comment]
This issue is related to #25. The latest release of awscli-login should resolve your issue. If not please file a new issue. Sorry for the delay in resolving this issue.
