### ISSUE TITLE
Potential dependency conflicts between awscli-login and botocore

### ISSUE THREAD

**Issue by NeolithEra** [techservicesillinois/awscli-login#37]
Hi, as shown in the following full dependency graph of  **_awscli-login_**, **_awscli-login_** requires **_botocore  *_** ， while the installed version of **_boto3_**(1.10.23) requires _**botocore >=1.13.23,<1.14.0**_.

According to Pip's _“first found wins”_ installation strategy, _**botocore 1.13.23**_ is the actually installed version.  

Although the first found package version _**botocore 1.13.23**_ just satisfies the later dependency constraint （_**botocore >=1.13.23,<1.14.0**_), it will lead to a build failure once developers release a newer version of botocore.

### Dependency tree--------
```
awscli-login - 0.1.0a6
| +- awscli(install version:1.16.287 version range:*)
| +- boto3(install version:1.10.23 version range:*)
| | +- botocore(install version:1.13.23 version range:>=1.13.23,<1.14.0)
| | | +- docutils(install version:0.15.2 version range:>=0.10,<0.16)
| | | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| | +- s3transfer(install version:0.2.1 version range:>=0.2.0,<0.3.0)
| | | +- botocore(install version:1.13.23 version range:<2.0.0,>=1.12.36)
| | | | +- docutils(install version:0.15.2 version range:>=0.10,<0.16)
| | | | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| +- botocore(install version:1.13.23 version range:*)
| | +- docutils(install version:0.15.2 version range:>=0.10,<0.16)
| | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| +- daemoniker(install version:0.2.3 version range:*)
| +- keyring(install version:19.2.0 version range:*)
| +- lxml(install version:4.4.1 version range:*)
| | +- cython(install version:0.29.14 version range:>=0.29.7)
| +- psutil(install version:5.6.7 version range:*)
| +- requests(install version:2.22.0 version range:*)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_botocore <1.14.0_**.
2.	Ask your upstream project **_boto3_** to lose the version range of **_botocore_** to be **_>=1.13.23_**, and **_s3transfer_** to lose the version range of **_botocore_** to be **_>=1.12.36_**.

@ddriddle Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by ddriddle** [comment]
@NeolithEra thank you for pointing out this dependency conflict and for your offer to address it with a pull request which are always welcome. I am resolving this issue by dropping the `boto3` library entirely (See #73). `botocore` offers all the functionality needed. Do you agree that this will resolve the issue you reported?
