### ISSUE TITLE
Consider logging configuration

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/awscli-login#4]
As currently released, the alpha version of this software maintains a session log.

This log is not located anywhere that's obvious to the end user, and will eventually grow in size.

Should the default behavior be to suppress logging? This could be developed with or without a global per-system configuration. (See #3.) My instinct tells me that debugging is the principal use case for logging, so logging probably doesn't make sense as the default.

**Comment by edthedev** [comment]
Moving this in with the planned error message work, as logging and error messaging share a concern with getting messages to users in an intentional way. 

I tend to agree we probably want to not keep a log file unless requested through configuration.
