### ISSUE TITLE
AuthnRequest IssueInstant generated is invalid due to missing timezone.

### ISSUE THREAD

**Issue by scantor** [techservicesillinois/awscli-login#41]
Your code is generating a zone-less ISO timestamp in the IssueInstant field of the request message, and that's invalid in SAML. It's also rejected by the V4 Shibboleth IdP because it interprets that as a UTC time instead of as local time, which is arbitrary but correct.

Just add a 'Z' on the end of the timestamp string it's generating and it should fix it.

**Comment by scantor** [comment]
Indeed, adding Z to the string in saml.py fixed the issue.

**Comment by lhoekenga** [comment]
When might this get released to PyPi?

**Comment by ddriddle** [comment]
@lhoekenga this change is on test pypi now and will be on pypi soon.

**Comment by ddriddle** [comment]
@lhoekenga this fix was released to PyPi yesterday.
