### ISSUE TITLE
FEATURE REQUEST: support for awscli v2

### ISSUE THREAD

**Issue by lhoekenga** [techservicesillinois/awscli-login#44]
Someone on our campus pointed out that awscli v2 is available and that this plugin does not (yet?) work with it..

https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/

**Comment by batmanthony** [comment]
+1

**Comment by Anjana-aws** [comment]
+1

**Comment by edthedev** [comment]
Here's documentation for the plugin changes:  
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-profile-plugins

**Comment by edthedev** [comment]
Looks like version 1 is still in general availability support, but new features are only being added to version 2.
https://docs.aws.amazon.com/cli/latest/userguide/welcome-versions.html

**Comment by Anjana-aws** [comment]
Thank you, Edward.

Best,
Anjana

Sent from my iPhone

On Dec 1, 2020, at 3:42 PM, Edward Delaporte <notifications@github.com> wrote:

﻿

Here's documentation for the plugin changes:
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-profile-plugins<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Fcli%2Flatest%2Fuserguide%2Fcliv2-migration.html%23cliv2-migration-profile-plugins&data=04%7C01%7Ca.ranganathan%40northeastern.edu%7C21359ce82f1c4333ff3708d89639add7%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637424521780336602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N5aeJ6QFZkCwxz0P%2BXofSorcuUD%2FUUsYG6fDjtx6GvM%3D&reserved=0>

**Comment by edthedev** [comment]
@ddriddle took an initial look at this. Not as trivial as we hoped, but looks doable.

**Comment by edthedev** [comment]
Did a quick-and-dirty estimate on this so it's ready for our future sprint planning.

**Comment by edthedev** [comment]
Remaining work before releasing this:

+ Remove our dependency on AWS CLI. 
+ Add a warning that reminds users to install their preferred version of AWS CLI.

**Comment by edthedev** [comment]
Note: When #73 gets merged, this plugin becomes compatible with AWS CLI V2.

**Comment by ddriddle** [comment]
A new release with full awscliv2 support has been released today, March 11, 2025, on PyPI. Installation instructions can be found here:

https://pypi.org/project/awscli-login/

Release notes and rollback instructions can be found here:

https://github.com/techservicesillinois/awscli-login/releases/tag/1.0
