### ISSUE TITLE
pypi install of 0.1.0a6 different than git

### ISSUE THREAD

**Issue by lhoekenga** [techservicesillinois/awscli-login#47]
The pypi install of awscli_login includes fixes for the spelling in the headers that don't seem to be present in "master", or the corresponding 0.1.0a6 tag. 

The code in git won't work with tokens or non-push authentication unless header names are changed in src/awscli_login/config.py OR shibboleth-idp/conf/authn/duo.properties.

Was the code in pypi pushed from a different fork?

[awscli_login.diff.txt](https://github.com/techservicesillinois/awscli-login/files/5632501/awscli_login.diff.txt)

**Comment by ddriddle** [comment]
@lhoekenga It was not pushed from a different fork but from a different branch. Probably from develop. I am planning on pushing out a new release very soon, that will use Github Actions to automatically push all future changes to PyPI test on merge to master, and to PyPI on tag to master, and run all automated tests on Linux/Mac/Windows. That should make sure issues like this do not arise again. Sorry for the confusion.

**Comment by lhoekenga** [comment]
@ddriddle I looked at what I thought was the right tag, but not the other branches.  Thanks for the the explanation.

**Comment by ddriddle** [comment]
@lhoekenga the `0.1.0a6` tag should now point to the correct code. I deleted the old tag, and pointed it to the correct branch. I also merged the 0.1.0a6 release into master. Everything should be clean and up to date in the repo. Sorry for the confusion, and thank you very much for pointing this out!

**Comment by lhoekenga** [comment]
Hey David -

Has this been released to pypy?

Liam

**Comment by ddriddle** [comment]
@lhoekenga Yes, it was released yesterday on PyPI: version 0.2b1. It should address the issues you were interested in seeing fixed. Going forward we should be able to get releases out much faster since the release process is now completely automated!
