### ISSUE TITLE
Wishlist - It would be cool for the AWS CLI login to automatically throw a warning when running under stale Python

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#82]
Since we know what version of Python an installation of AWS CLI was last tested under (i.e. Python 3.9 if you installed the latest release today), we could add a soft warning message for when it finds itself running under a newer version. The message could encourage checking for an update from PyPI (possibly helping any future security fixes reach clients sooner).

This is just a nice to have, but it would be a good practice to incorporate, and it would be nice to have public example code to point other teams to who need a similar solution. 

We should research what other teams have done in Python (I believe I have seen similar messages, but need to remember where), and replicate best practices we find elsewhere that address this functionality.

**Comment by JonRoma** [comment]
@edthedev, one of the examples that comes to mind is `pip` itself reporting that there is a new version of `pip` available. I don't know how this works, but I guess the source code will solve that question! :-)

Maybe I misunderstood your question, but the above would be handy as a way of reminding users that there's a new version of the package available. I just had another person report the Shibboleth 500 error to me this afternoon, so I can see the value in this down the road.
