### ISSUE TITLE
Dependency version conflict error with 

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/awscli-login#83]
While attempting to do a `pip install --upgrade awscli-login`on a newly-booted Amazon EC2 instance, we encountered a dependency error that does not seem to be documented in the package's `setup.py`.

In a nutshell, the package demands`setuptools>=45`, but raises an exception because the version of `setuptools` in the AWS installation is too old to be compatible (version 36.2.7). An additional exception occurred while handling the `VersionConflict` exception. The result of this issue is that an outdated awscli-login (version 0.2b1) isn't upgraded. With the Shibboleth IdP migration to the AWS cloud this morning 3/24/2021, the legacy version of the plugin does not work with the updated IdP.

This issue will therefore affect anyone using the old plugin who also hasn't explicitly updated setuptools.

A manual workaround is possible by doing `pip install --upgrade setuptools`, but naturally, the dependency detection and resolution should take place automatically – particularly since this cloud infrastructure will be spun up and down repeatedly.

This is on Amazon Linux with the description "Amazon Linux AMI 2018.03.0.20210319.0 x86_64 HVM gp2" and AMI `ami-03c097d564dea7d12`. We're using Python 3.8 and pip 3.8.

A snippet of the exception traceback is attached; the entire traceback is included as an attachment.

If needed for debugging, I can reproduce this environment and make available to the Security Development team.

```
Requirement already satisfied: awscli-login in /usr/local/lib/python3.8/site-packages (0.1.0a6)
Collecting awscli-login
  Using cached awscli-login-0.2b1.tar.gz (59 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w4ya16hv/awscli-login_a85ff6b460b34a4a84e613ebcb0fea67/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w4ya16hv/awscli-login_a85ff6b460b34a4a84e613ebcb0fea67/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mr5f6hqy
         cwd: /tmp/pip-install-w4ya16hv/awscli-login_a85ff6b460b34a4a84e613ebcb0fea67/
    Complete output (94 lines):
    Traceback (most recent call last):
      File "/usr/lib/python3.8/dist-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/usr/lib/python3.8/dist-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib/python3.8/dist-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.8/dist-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ap0y5uxr/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        install_requires=[
      File "/usr/lib64/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.8/dist-packages/setuptools/dist.py", line 328, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib64/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3.8/dist-packages/setuptools/dist.py", line 460, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2338, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 863, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (setuptools 36.2.7 (/usr/lib/python3.8/dist-packages), Requirement.parse('setuptools>=45'))

    During handling of the above exception, another exception occurred:
```

*ad nauseum*

[pip.txt](https://github.com/techservicesillinois/awscli-login/files/6200574/pip.txt)

**Comment by kwessel** [comment]
I suspect this is a relatively low priority issue. All users of AWSCLI were told to upgrade over a month ago via a message to techsupport. If they tried and it failed to upgrade, they would have either been with-it enough to manually upgrade setuptools based on the error message or would have reached out to IAMU. Of course, based on some of the folks who have reported this issue so far, it's clear that they either aren't on the techsupport list or ignored that note, or ossibly they tried to upgrade and ignored the fact that it failed.

Regardless, IAMU will be on the look-out for reports of this issue until it's fixed.

**Comment by JonRoma** [comment]
Sighted people might easily miss the error messages spewing to the terminal by pip. In spite of being displayed in red, you actually have to scroll back through a lot of noise to notice that it failed. It in fact took me a while to grasp what was going on.

**Comment by JonRoma** [comment]
As for priority, I'll leave that for @edthedev and their team to determine. They have been doing major maintenance to a useful product that was suffering benign neglect for a long time. The plugin has a constituency beyond UIUC and thus includes users who don't use our IdP and who did not receive your mail.

**Comment by kwessel** [comment]
Regardless, I would hope “sighted people” would wonder why a big error scrolled on their screen and would either ask us or would scroll back through. I’m not saying this doesn’t need to be fixed; I’m just saying it’s not a big deal. And so far, IAMU hasn’t heard from anyone. Thanks for the guidance on what to tell them if we do, though.

**Comment by kwessel** [comment]
Agreed. Just saying from a production issue, this isn’t a priority, or at least not a big deal.

**Comment by edthedev** [comment]
In light of @JonRoma's point about our external audience not being on @kwessel's very helpful email notifications, I have opened a pull request to put a suggestion toward the top of the `install` section to help our users avoid this issue.

This isn't meant to be instead of a more definitive solution, but to be a quick way to save some folks a potential headache.

**Comment by edthedev** [comment]
Merging closed this automatically, but I want to hold it open for a bit more analysis.

**Comment by edthedev** [comment]
Re-closing this for now, as I think we are past the issue.  Feel free to re-open if this is encountered again.

**Comment by ddriddle** [comment]
@edthedev and @JonRoma there are some technical solutions to this problem that are discussed here:

https://stackoverflow.com/questions/48048745/setup-py-require-a-recent-version-of-setuptools-before-trying-to-install

> While attempting to do a pip install --upgrade awscli-loginon a newly-booted Amazon EC2 instance, we encountered a dependency error that does not seem to be documented in the package's setup.py.

`setuptools` is not a runtime dependency of awscli-login, but it is a dependency for the build process. Unfortunately, `setup.py` provides no mechanism for specifying build dependencies, only runtime dependencies. I could add a `pyproject.toml` file per [PEP 518](https://www.python.org/dev/peps/pep-0518/) but that will not help you if you are using an old version of PIP (Prior to [2017](https://github.com/pypa/pip/pull/4144#issuecomment-263653485)).

> A manual workaround is possible by doing pip install --upgrade setuptools, but naturally, the dependency detection and resolution should take place automatically – particularly since this cloud infrastructure will be spun up and down repeatedly.

I could add a manual check in the setup.py, but that will just cause it to error out with a better message. Not sure if that is worth it. Probably the best thing is for you to upgrade pip and setuptools, and for us to add a `pyproject.toml` file per PEP 518.

**Comment by JonRoma** [comment]
Is this of any use?

https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html

Frankly, if someone hasn't upgraded `pip` since 2017, I have not a bit of sympathy for them. :-)

**Comment by ddriddle** [comment]
@JonRoma thanks for the link. I have opened issue #90 to add a `pyproject.toml` file. I think explicitly documenting the build requirements is a good thing. I'm not sure if it will help your original situation though. It might if your pip is recent enough.

**Comment by ddriddle** [comment]
@JonRoma I was thinking about this more, and I was wondering why pip needed `setuptools`, which is a build dependency not a runtime one, and why it was looking at the `setup.py`. The reason is because pip is trying to install from source, notice in the logs the tar ball:

```
Requirement already satisfied: awscli-login in /usr/local/lib/python3.8/site-packages (0.1.0a6)
Collecting awscli-login
  Using cached awscli-login-0.2b1.tar.gz (59 kB)
...
```

That necessitates a build which requires `setuptools`. The reason pip is pulling the source instead of a wheel is because I failed to upload a wheel for version 0.2b1 which can be seen clearly on PyPI:

https://pypi.org/project/awscli-login/0.2b1/#files

The previous has both source and a wheel:

https://pypi.org/project/awscli-login/0.1.0a6/#files

@JonRoma If the lack of a wheel is still causing problems I can upload one for version `0.2b1`.

**Comment by JonRoma** [comment]
@ddriddle, it only caused problem the first time when I had to forcibly upgrade setuptools. It's thus not necessary to upload a wheel for 0.2b1, but it would be nice to do that for future releases.

BTW, do you know how to upload a wheel to the "Releases" section of a repo along with the zip and tar.gz? That's something I'd like to do for some of our repos that don't go up on PyPI. Thanks.

**Comment by ddriddle** [comment]
@JonRoma I filled a ticket #91 to address the lack of a wheel. I will get that fixed before the next release.

I have not done much with releases, but my understanding is you can attach pretty much anything you want to them so it should be straightforward to attach a wheel. It looks pretty simple in the GUI: just drag and drop. I have not tried automating the process.

**Comment by JonRoma** [comment]
@ddriddle, I'm definitely interested in automation, because with wheels published to GitHub, we could probably retire the SDG pip server.
