### ISSUE TITLE
Ensure that wheel and source is uploaded to PyPI

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/awscli-login#91]
The last release is source only as are all the recent releases on test PyPI:

https://pypi.org/project/awscli-login/0.2b1/#files

https://test.pypi.org/project/awscli-login/0.2b2.dev10/#files

The last release to include both source and a wheel was v0.1.0a6:

https://pypi.org/project/awscli-login/0.1.0a6/#files

Review and fix the release process so that both the source and wheel are released to both PyPI and test PyPI.

**Comment by JonRoma** [comment]
@ddriddle, is there any likelihood of a quick fix for this issue? Ideally, it would be nice to avoid a somewhat awkward workaround. This has confounded a few people installing the plugin on EC2.
