### ISSUE TITLE
AWS CLI V2 support: is it supported now?

### ISSUE THREAD

**Issue by knoxilla** [techservicesillinois/awscli-login#95]
Great tool - been using it for some years now very happily.

I see from the convo in issue #44 that you have been at work on this, and PR #73 is the point at which the plugin will be compatible with AWS CLI V2.  The PR is merged and the issue is closed but I'm not sure how to make this work.

Since moving to the CLI V2 I've kept a V1 binary in the path so I can use _it_ and the awscli-login plugin to get credentials a la 

`aws-v1 login`

Then I just switch to the regular `aws` command for everything else except `aws-v1 logout`.  Works fine, but I'd sure like to just use V2.

Can you tell me what I'm missing about using this plugin with V2?

**Comment by edthedev** [comment]
@knoxilla Thanks for the feedback! Yes - we need to do a quick pass through the documentation on setting this up, and ensure there are no remaining blockers.

## Tasks

+ [ ] remove dependency on AWS CLI V1.
+ [ ] Update the documentation for use with AWS CLI V2.

**Comment by ddriddle** [comment]
@knoxilla we have merged V2 support into mainline. It is available for testing on [test PyPI](https://test.pypi.org/project/awscli-login/), and a production release should be available by the end of the month.

**Comment by ddriddle** [comment]
A new release with full awscliv2 support has been released today, March 11, 2025, on PyPI. Installation instructions can be found here:

https://pypi.org/project/awscli-login/

Release notes and rollback instructions can be found here:

https://github.com/techservicesillinois/awscli-login/releases/tag/1.0
